jobscheduler-master:
  build: master
  links:
    - db:mysql
  volumes_from:
    - datastore
  ports:
    - "4444:4444"
    - "40444:40444"

jobscheduler-joc:
  build: joc
  links:
    - db:mysql
    - jobscheduler-master
  volumes_from:
    - datastore
  ports:
    - "4446:4446"
db:
  image: mariadb:latest
  environment:
    MYSQL_USER: jobscheduler
    MYSQL_PASSWORD: jobscheduler
    MYSQL_ROOT_PASSWORD: scheduler
    MYSQL_DATABASE: jobscheduler

datastore:
   image: busybox
   command: /bin/true
   volumes:
     - /opt/jobscheduler/data/scheduler/config/live
